export const TOOL_NAMES = [
  'proxmox_node',
  'proxmox_cluster',
  'proxmox_get_node_services',
  'proxmox_control_node_service',
  'proxmox_get_node_syslog',
  'proxmox_get_node_journal',
  'proxmox_get_node_tasks',
  'proxmox_get_node_task',
  'proxmox_get_node_aplinfo',
  'proxmox_get_node_netstat',
  'proxmox_get_node_rrddata',
  'proxmox_get_storage_rrddata',
  'proxmox_get_node_report',
  'proxmox_create_network_iface',
  'proxmox_update_network_iface',
  'proxmox_delete_network_iface',
  'proxmox_apply_network_config',
  'proxmox_get_node_time',
  'proxmox_update_node_time',
  'proxmox_update_node_dns',
  'proxmox_get_node_hosts',
  'proxmox_update_node_hosts',
  'proxmox_get_node_subscription',
  'proxmox_set_node_subscription',
  'proxmox_delete_node_subscription',
  'proxmox_apt_update',
  'proxmox_apt_upgrade',
  'proxmox_apt_versions',
  'proxmox_start_all',
  'proxmox_stop_all',
  'proxmox_migrate_all',
  'proxmox_node_shutdown',
  'proxmox_node_reboot',
  'proxmox_node_wakeonlan',
  'proxmox_get_node_replication_status',
  'proxmox_get_node_replication_log',
  'proxmox_schedule_node_replication',
  'proxmox_guest_list',
  'proxmox_guest_status',
  'proxmox_guest_config',
  'proxmox_guest_pending',
  'proxmox_guest_feature',
  'proxmox_guest_rrddata',
  'proxmox_execute_vm_command',
  'proxmox_get_storage',
  'proxmox_list_templates',
  'proxmox_create_lxc',
  'proxmox_create_vm',
  'proxmox_get_next_vmid',
  'proxmox_ha_resource',
  'proxmox_ha_group',
  'proxmox_cluster_firewall_rule',
  'proxmox_cluster_firewall_group',
  'proxmox_cluster_firewall',
  'proxmox_cluster_firewall_alias',
  'proxmox_cluster_firewall_ipset',
  'proxmox_cluster_firewall_ipset_entry',
  'proxmox_cluster_backup_job',
  'proxmox_cluster_replication_job',
  'proxmox_cluster_config',
  'proxmox_sdn_vnet',
  'proxmox_sdn_zone',
  'proxmox_sdn_controller',
  'proxmox_sdn_subnet',
  'proxmox_user',
  'proxmox_group',
  'proxmox_role',
  'proxmox_acl',
  'proxmox_domain',
  'proxmox_user_token',
  'proxmox_pool',
  'proxmox_storage_config',
  'proxmox_storage_content',
  'proxmox_list_file_restore',
  'proxmox_download_file_restore',
  'proxmox_ceph',
  'proxmox_ceph_osd',
  'proxmox_ceph_mon',
  'proxmox_ceph_mds',
  'proxmox_ceph_pool',
  'proxmox_ceph_fs',
  'proxmox_guest_start',
  'proxmox_guest_stop',
  'proxmox_guest_reboot',
  'proxmox_guest_shutdown',
  'proxmox_guest_delete',
  'proxmox_guest_pause',
  'proxmox_guest_resume',
  'proxmox_guest_clone',
  'proxmox_guest_resize',
  'proxmox_guest_config_update',
  'proxmox_guest_migrate',
  'proxmox_guest_template',

  'proxmox_agent_ping',
  'proxmox_agent_get_osinfo',
  'proxmox_agent_get_fsinfo',
  'proxmox_agent_get_memory_blocks',
  'proxmox_agent_get_network_interfaces',
  'proxmox_agent_get_time',
  'proxmox_agent_get_timezone',
  'proxmox_agent_get_vcpus',
  'proxmox_agent_exec',
  'proxmox_agent_exec_status',
  'proxmox_agent_file_read',
  'proxmox_agent_file_write',
  'proxmox_agent_get_hostname',
  'proxmox_agent_get_users',
  'proxmox_agent_set_user_password',
  'proxmox_agent_shutdown',
  'proxmox_agent_fsfreeze_status',
  'proxmox_agent_fsfreeze_freeze',
  'proxmox_agent_fsfreeze_thaw',
  'proxmox_agent_fstrim',
  'proxmox_agent_get_memory_block_info',
  'proxmox_agent_suspend_disk',
  'proxmox_agent_suspend_ram',
  'proxmox_agent_suspend_hybrid',
  'proxmox_list_vm_firewall_rules',
  'proxmox_get_vm_firewall_rule',
  'proxmox_create_vm_firewall_rule',
  'proxmox_update_vm_firewall_rule',
  'proxmox_delete_vm_firewall_rule',
  'proxmox_list_lxc_firewall_rules',
  'proxmox_get_lxc_firewall_rule',
  'proxmox_create_lxc_firewall_rule',
  'proxmox_update_lxc_firewall_rule',
  'proxmox_delete_lxc_firewall_rule',
  'proxmox_get_vnc_proxy',
  'proxmox_get_spice_proxy',
  'proxmox_get_term_proxy',
  'proxmox_get_lxc_vnc_proxy',
  'proxmox_get_lxc_term_proxy',
  'proxmox_guest_snapshot',
  'proxmox_backup',
  'proxmox_add_disk_vm',
  'proxmox_add_mountpoint_lxc',
  'proxmox_resize_disk_vm',
  'proxmox_resize_disk_lxc',
  'proxmox_remove_disk_vm',
  'proxmox_remove_mountpoint_lxc',
  'proxmox_move_disk_vm',
  'proxmox_move_disk_lxc',
  'proxmox_add_network_vm',
  'proxmox_add_network_lxc',
  'proxmox_update_network_vm',
  'proxmox_update_network_lxc',
  'proxmox_remove_network_vm',
  'proxmox_remove_network_lxc',
  'proxmox_get_node_disks',
  'proxmox_get_disk_smart',
  'proxmox_get_node_lvm',
  'proxmox_get_node_zfs',
  'proxmox_init_disk_gpt',
  'proxmox_wipe_disk',
  'proxmox_get_node_lvmthin',
  'proxmox_get_node_directory',
  // Cloud-Init
  'proxmox_get_cloudinit_config',
  'proxmox_dump_cloudinit',
  'proxmox_regenerate_cloudinit',
  // Certificate Management
  'proxmox_get_node_certificates',
  'proxmox_upload_custom_certificate',
  'proxmox_delete_custom_certificate',
  'proxmox_order_acme_certificate',
  'proxmox_renew_acme_certificate',
  'proxmox_revoke_acme_certificate',
  'proxmox_get_node_acme_config',
  // ACME Management
  'proxmox_list_acme_accounts',
  'proxmox_get_acme_account',
  'proxmox_create_acme_account',
  'proxmox_update_acme_account',
  'proxmox_delete_acme_account',
  'proxmox_list_acme_plugins',
  'proxmox_get_acme_plugin',
  'proxmox_get_acme_directories',
  // Notification Management
  'proxmox_list_notification_targets',
  'proxmox_get_notification_target',
  'proxmox_create_notification_target',
  'proxmox_delete_notification_target',
  'proxmox_test_notification_target',
] as const;

export type ToolName = (typeof TOOL_NAMES)[number];

export type PermissionLevel = 'basic' | 'elevated';

export interface ToolResponse {
  content: Array<{
    type: 'text';
    text: string;
  }>;
  isError?: boolean;
}

export function createToolResponse(text: string, isError = false): ToolResponse {
  return {
    content: [{ type: 'text', text }],
    isError,
  };
}
