import type { ProxmoxApiClient } from '../client/proxmox.js';
import type { Config } from '../config/index.js';
import type { ToolResponse, ToolName } from '../types/index.js';
import type { z } from 'zod';

// Import all tool handlers
import {
  getNodes,
  getNodeStatus,
  getNodeNetwork,
  getNodeDns,
  getNetworkIface,
  getNodeServices,
  controlNodeService,
  getNodeSyslog,
  getNodeJournal,
  getNodeTasks,
  getNodeTask,
  getNodeAplinfo,
  getNodeNetstat,
  getNodeRrddata,
  getStorageRrddata,
  getNodeReport,
  createNetworkIface,
  updateNetworkIface,
  deleteNetworkIface,
  applyNetworkConfig,
  getNodeTime,
  updateNodeTime,
  updateNodeDns,
  getNodeHosts,
  updateNodeHosts,
  getNodeSubscription,
  setNodeSubscription,
  deleteNodeSubscription,
  aptUpdate,
  aptUpgrade,
  aptVersions,
  startAll,
  stopAll,
  migrateAll,
  nodeShutdown,
  nodeReboot,
  nodeWakeonlan,
  getNodeReplicationStatus,
  getNodeReplicationLog,
  scheduleNodeReplication,
  getClusterStatus,
  getNextVMID,
  getHaResources,
  getHaResource,
  createHaResource,
  updateHaResource,
  deleteHaResource,
  getHaGroups,
  getHaGroup,
  createHaGroup,
  updateHaGroup,
  deleteHaGroup,
  getHaStatus,
  listClusterFirewallRules,
  getClusterFirewallRule,
  createClusterFirewallRule,
  updateClusterFirewallRule,
  deleteClusterFirewallRule,
  listClusterFirewallGroups,
  getClusterFirewallGroup,
  createClusterFirewallGroup,
  updateClusterFirewallGroup,
  deleteClusterFirewallGroup,
  listClusterBackupJobs,
  getClusterBackupJob,
  createClusterBackupJob,
  updateClusterBackupJob,
  deleteClusterBackupJob,
  listClusterReplicationJobs,
  getClusterReplicationJob,
  createClusterReplicationJob,
  updateClusterReplicationJob,
  deleteClusterReplicationJob,
  getClusterOptions,
  updateClusterOptions,
  getClusterFirewallOptions,
  updateClusterFirewallOptions,
   listClusterFirewallMacros,
   listClusterFirewallRefs,
   listClusterFirewallAliases,
   getClusterFirewallAlias,
   createClusterFirewallAlias,
   updateClusterFirewallAlias,
   deleteClusterFirewallAlias,
   listClusterFirewallIpsets,
   createClusterFirewallIpset,
   deleteClusterFirewallIpset,
   listClusterFirewallIpsetEntries,
   addClusterFirewallIpsetEntry,
   updateClusterFirewallIpsetEntry,
   deleteClusterFirewallIpsetEntry,
   listSdnVnets,
  getSdnVnet,
  createSdnVnet,
  updateSdnVnet,
  deleteSdnVnet,
  listSdnZones,
  getSdnZone,
  createSdnZone,
  updateSdnZone,
  deleteSdnZone,
  listSdnControllers,
  getSdnController,
  createSdnController,
  updateSdnController,
  deleteSdnController,
  listSdnSubnets,
  getSdnSubnet,
  createSdnSubnet,
  updateSdnSubnet,
  deleteSdnSubnet,
  listUsers,
  getUser,
  createUser,
  updateUser,
  deleteUser,
  listGroups,
  createGroup,
  updateGroup,
  deleteGroup,
  listRoles,
  createRole,
  updateRole,
  deleteRole,
  getAcl,
  updateAcl,
  listDomains,
  getDomain,
  createDomain,
  updateDomain,
  deleteDomain,
  listUserTokens,
  getUserToken,
  createUserToken,
  updateUserToken,
  deleteUserToken,
  listPools,
  getPool,
  createPool,
  updatePool,
  deletePool,
  listStorageConfig,
  getStorageConfig,
  createStorage,
  updateStorage,
  deleteStorage,
  uploadToStorage,
  downloadUrlToStorage,
  listStorageContent,
  deleteStorageContent,
  listFileRestore,
  downloadFileRestore,
  pruneBackups,
  getCephStatus,
  listCephOsds,
  createCephOsd,
  deleteCephOsd,
  listCephMons,
  createCephMon,
  deleteCephMon,
  listCephMds,
  createCephMds,
  deleteCephMds,
  listCephPools,
  createCephPool,
  updateCephPool,
  deleteCephPool,
  listCephFs,
  createCephFs,
  getVMs,
  getVMStatus,
  getVMConfig,
  getLxcConfig,
  getStorage,
  startLxc,
  startVM,
  stopLxc,
  stopVM,
  deleteLxc,
  deleteVM,
  rebootLxc,
  rebootVM,
  shutdownLxc,
  shutdownVM,
  pauseVM,
  resumeVM,
  cloneLxc,
  cloneVM,
  resizeLxc,
  resizeVM,
  migrateVm,
  migrateLxc,
  createTemplateVm,
  createTemplateLxc,
  getVmRrddata,
  getLxcRrddata,
  agentPing,
  agentGetOsinfo,
  agentGetFsinfo,
  agentGetMemoryBlocks,
  agentGetNetworkInterfaces,
  agentGetTime,
  agentGetTimezone,
  agentGetVcpus,
   agentExec,
   agentExecStatus,
   agentFileRead,
   agentFileWrite,
   agentGetHostname,
   agentGetUsers,
   agentSetUserPassword,
   agentShutdown,
   agentFsfreezeStatus,
   agentFsfreezeFreeze,
   agentFsfreezeThaw,
   agentFstrim,
   agentGetMemoryBlockInfo,
   agentSuspendDisk,
   agentSuspendRam,
   agentSuspendHybrid,
   listVmFirewallRules,
  getVmFirewallRule,
  createVmFirewallRule,
  updateVmFirewallRule,
  deleteVmFirewallRule,
  listLxcFirewallRules,
  getLxcFirewallRule,
  createLxcFirewallRule,
  updateLxcFirewallRule,
  deleteLxcFirewallRule,
  getVncProxy,
  getSpiceProxy,
  getTermProxy,
  getLxcVncProxy,
  getLxcTermProxy,
  createSnapshotLxc,
  createSnapshotVM,
  listSnapshotsLxc,
  listSnapshotsVM,
  rollbackSnapshotLxc,
  rollbackSnapshotVM,
  deleteSnapshotLxc,
  deleteSnapshotVM,
  createBackupLxc,
  createBackupVM,
  listBackups,
  restoreBackupLxc,
  restoreBackupVM,
  deleteBackup,
  addDiskVM,
  addMountpointLxc,
  resizeDiskVM,
  resizeDiskLxc,
  removeDiskVM,
  removeMountpointLxc,
  moveDiskVM,
  moveDiskLxc,
  getNodeDisks,
  getDiskSmart,
  getNodeLvm,
  getNodeZfs,
  addNetworkVm,
  addNetworkLxc,
  updateNetworkVm,
  updateNetworkLxc,
  removeNetworkVm,
  removeNetworkLxc,
  executeVMCommand,
  listTemplates,
  createLxc,
  createVM,
  getCloudInitConfig,
  dumpCloudInit,
  regenerateCloudInit,
} from './index.js';

// Import all schemas
import {
  getNodesSchema,
  getNodeStatusSchema,
  getNodeNetworkSchema,
  getNodeDnsSchema,
  getNetworkIfaceSchema,
  getNodeServicesSchema,
  controlNodeServiceSchema,
  getNodeSyslogSchema,
  getNodeJournalSchema,
  getNodeTasksSchema,
  getNodeTaskSchema,
  getNodeAplinfoSchema,
  getNodeNetstatSchema,
  getNodeRrddataSchema,
  getStorageRrddataSchema,
  getNodeReportSchema,
  getClusterStatusSchema,
  getNextVmidSchema,
} from '../schemas/node.js';
import {
  createNetworkIfaceSchema,
  updateNetworkIfaceSchema,
  deleteNetworkIfaceSchema,
  applyNetworkConfigSchema,
} from '../schemas/node-network.js';
import {
  getNodeTimeSchema,
  updateNodeTimeSchema,
  updateNodeDnsSchema,
  getNodeHostsSchema,
  updateNodeHostsSchema,
  getNodeSubscriptionSchema,
  setNodeSubscriptionSchema,
  deleteNodeSubscriptionSchema,
  aptUpdateSchema,
  aptUpgradeSchema,
  aptVersionsSchema,
  startAllSchema,
  stopAllSchema,
  migrateAllSchema,
  nodeShutdownSchema,
  nodeRebootSchema,
  nodeWakeonlanSchema,
  getNodeReplicationStatusSchema,
  getNodeReplicationLogSchema,
  scheduleNodeReplicationSchema,
} from '../schemas/system-operations.js';
import {
  getHaResourcesSchema,
  getHaResourceSchema,
  createHaResourceSchema,
  updateHaResourceSchema,
  deleteHaResourceSchema,
  getHaGroupsSchema,
  getHaGroupSchema,
  createHaGroupSchema,
  updateHaGroupSchema,
  deleteHaGroupSchema,
  getHaStatusSchema,
  listClusterFirewallRulesSchema,
  getClusterFirewallRuleSchema,
  createClusterFirewallRuleSchema,
  updateClusterFirewallRuleSchema,
  deleteClusterFirewallRuleSchema,
  listClusterFirewallGroupsSchema,
  getClusterFirewallGroupSchema,
  createClusterFirewallGroupSchema,
  updateClusterFirewallGroupSchema,
  deleteClusterFirewallGroupSchema,
  listClusterBackupJobsSchema,
  getClusterBackupJobSchema,
  createClusterBackupJobSchema,
  updateClusterBackupJobSchema,
  deleteClusterBackupJobSchema,
  listClusterReplicationJobsSchema,
  getClusterReplicationJobSchema,
  createClusterReplicationJobSchema,
  updateClusterReplicationJobSchema,
  deleteClusterReplicationJobSchema,
  getClusterOptionsSchema,
  updateClusterOptionsSchema,
  getClusterFirewallOptionsSchema,
  updateClusterFirewallOptionsSchema,
   listClusterFirewallMacrosSchema,
   listClusterFirewallRefsSchema,
   listClusterFirewallAliasesSchema,
   getClusterFirewallAliasSchema,
   createClusterFirewallAliasSchema,
   updateClusterFirewallAliasSchema,
   deleteClusterFirewallAliasSchema,
   listClusterFirewallIpsetsSchema,
   createClusterFirewallIpsetSchema,
   deleteClusterFirewallIpsetSchema,
   listClusterFirewallIpsetEntriesSchema,
   addClusterFirewallIpsetEntrySchema,
   updateClusterFirewallIpsetEntrySchema,
   deleteClusterFirewallIpsetEntrySchema,
 } from '../schemas/cluster-management.js';
import {
  listSdnVnetsSchema,
  getSdnVnetSchema,
  createSdnVnetSchema,
  updateSdnVnetSchema,
  deleteSdnVnetSchema,
  listSdnZonesSchema,
  getSdnZoneSchema,
  createSdnZoneSchema,
  updateSdnZoneSchema,
  deleteSdnZoneSchema,
  listSdnControllersSchema,
  getSdnControllerSchema,
  createSdnControllerSchema,
  updateSdnControllerSchema,
  deleteSdnControllerSchema,
  listSdnSubnetsSchema,
  getSdnSubnetSchema,
  createSdnSubnetSchema,
  updateSdnSubnetSchema,
  deleteSdnSubnetSchema,
} from '../schemas/sdn.js';
import {
  listUsersSchema,
  getUserSchema,
  createUserSchema,
  updateUserSchema,
  deleteUserSchema,
  listGroupsSchema,
  createGroupSchema,
  updateGroupSchema,
  deleteGroupSchema,
  listRolesSchema,
  createRoleSchema,
  updateRoleSchema,
  deleteRoleSchema,
  getAclSchema,
  updateAclSchema,
  listDomainsSchema,
  getDomainSchema,
  createDomainSchema,
  updateDomainSchema,
  deleteDomainSchema,
  listUserTokensSchema,
  getUserTokenSchema,
  createUserTokenSchema,
  updateUserTokenSchema,
  deleteUserTokenSchema,
} from '../schemas/access-control.js';
import {
  listPoolsSchema,
  getPoolSchema,
  createPoolSchema,
  updatePoolSchema,
  deletePoolSchema,
} from '../schemas/pool-management.js';
import {
  listStorageConfigSchema,
  getStorageConfigSchema,
  createStorageSchema,
  updateStorageSchema,
  deleteStorageSchema,
  uploadToStorageSchema,
  downloadUrlToStorageSchema,
  listStorageContentSchema,
  deleteStorageContentSchema,
  listFileRestoreSchema,
  downloadFileRestoreSchema,
  pruneBackupsSchema,
} from '../schemas/storage-management.js';
import {
  getCephStatusSchema,
  listCephOsdsSchema,
  createCephOsdSchema,
  deleteCephOsdSchema,
  listCephMonsSchema,
  createCephMonSchema,
  deleteCephMonSchema,
  listCephMdsSchema,
  createCephMdsSchema,
  deleteCephMdsSchema,
  listCephPoolsSchema,
  createCephPoolSchema,
  updateCephPoolSchema,
  deleteCephPoolSchema,
  listCephFsSchema,
  createCephFsSchema,
} from '../schemas/ceph.js';
import {
  getVmsSchema,
  getVmStatusSchema,
  getVmConfigSchema,
  getLxcConfigSchema,
  getStorageSchema,
  startLxcSchema,
  startVmSchema,
  stopLxcSchema,
  stopVmSchema,
  deleteLxcSchema,
  deleteVmSchema,
  rebootLxcSchema,
  rebootVmSchema,
  shutdownLxcSchema,
  shutdownVmSchema,
  pauseVmSchema,
  resumeVmSchema,
  cloneLxcSchema,
  cloneVmSchema,
  resizeLxcSchema,
  resizeVmSchema,
  executeVmCommandSchema,
  listTemplatesSchema,
  createLxcSchema,
  createVmSchema,
} from '../schemas/vm.js';
import {
  migrateVmSchema,
  migrateLxcSchema,
  createTemplateVmSchema,
  createTemplateLxcSchema,
  getVmRrddataSchema,
  getLxcRrddataSchema,
  agentPingSchema,
  agentGetOsinfoSchema,
  agentGetFsinfoSchema,
  agentGetMemoryBlocksSchema,
  agentGetNetworkInterfacesSchema,
  agentGetTimeSchema,
  agentGetTimezoneSchema,
  agentGetVcpusSchema,
   agentExecSchema,
   agentExecStatusSchema,
   agentFileReadSchema,
   agentFileWriteSchema,
   agentGetHostnameSchema,
   agentGetUsersSchema,
   agentSetUserPasswordSchema,
   agentShutdownSchema,
  agentFsfreezeStatusSchema,
  agentFsfreezeFreezeSchema,
  agentFsfreezeThawSchema,
  agentFstrimSchema,
  agentGetMemoryBlockInfoSchema,
  agentSuspendDiskSchema,
  agentSuspendRamSchema,
  agentSuspendHybridSchema,
   listVmFirewallRulesSchema,
  getVmFirewallRuleSchema,
  createVmFirewallRuleSchema,
  updateVmFirewallRuleSchema,
  deleteVmFirewallRuleSchema,
  listLxcFirewallRulesSchema,
  getLxcFirewallRuleSchema,
  createLxcFirewallRuleSchema,
  updateLxcFirewallRuleSchema,
  deleteLxcFirewallRuleSchema,
} from '../schemas/vm-advanced.js';
import {
  createSnapshotLxcSchema,
  createSnapshotVmSchema,
  listSnapshotsLxcSchema,
  listSnapshotsVmSchema,
  rollbackSnapshotLxcSchema,
  rollbackSnapshotVmSchema,
  deleteSnapshotLxcSchema,
  deleteSnapshotVmSchema,
} from '../schemas/snapshot.js';
import {
  createBackupLxcSchema,
  createBackupVmSchema,
  listBackupsSchema,
  restoreBackupLxcSchema,
  restoreBackupVmSchema,
  deleteBackupSchema,
} from '../schemas/backup.js';
import {
  addDiskVmSchema,
  addMountpointLxcSchema,
  resizeDiskVmSchema,
  resizeDiskLxcSchema,
  removeDiskVmSchema,
  removeMountpointLxcSchema,
  moveDiskVmSchema,
  moveDiskLxcSchema,
  getNodeDisksSchema,
  getDiskSmartSchema,
  getNodeLvmSchema,
  getNodeZfsSchema,
} from '../schemas/disk.js';
import {
  addNetworkVmSchema,
  addNetworkLxcSchema,
  updateNetworkVmSchema,
  updateNetworkLxcSchema,
  removeNetworkVmSchema,
  removeNetworkLxcSchema,
} from '../schemas/network.js';
import {
  getVncProxySchema,
  getSpiceProxySchema,
  getTermProxySchema,
  getLxcVncProxySchema,
  getLxcTermProxySchema,
} from '../schemas/console-access.js';
import {
  getCloudInitConfigSchema,
  dumpCloudInitSchema,
  regenerateCloudInitSchema,
} from '../schemas/cloud-init.js';

// Tool handler type - accepts any input type for flexibility
export type ToolHandler = (
  client: ProxmoxApiClient,
  config: Config,
  input: any
) => Promise<ToolResponse>;

// Registry entry type
export interface ToolRegistryEntry {
  handler: ToolHandler;
  schema: z.ZodSchema;
}

// Tool registry mapping tool names to handlers and schemas
export const toolRegistry: Record<ToolName, ToolRegistryEntry> = {
  // Node & Cluster
  proxmox_get_nodes: { handler: getNodes, schema: getNodesSchema },
  proxmox_get_node_status: { handler: getNodeStatus, schema: getNodeStatusSchema },
  proxmox_get_node_network: { handler: getNodeNetwork, schema: getNodeNetworkSchema },
  proxmox_get_node_dns: { handler: getNodeDns, schema: getNodeDnsSchema },
  proxmox_get_network_iface: { handler: getNetworkIface, schema: getNetworkIfaceSchema },
  proxmox_get_cluster_status: { handler: getClusterStatus, schema: getClusterStatusSchema },
  proxmox_get_next_vmid: { handler: getNextVMID, schema: getNextVmidSchema },

  // Node Network Configuration
  proxmox_create_network_iface: {
    handler: createNetworkIface,
    schema: createNetworkIfaceSchema,
  },
  proxmox_update_network_iface: {
    handler: updateNetworkIface,
    schema: updateNetworkIfaceSchema,
  },
  proxmox_delete_network_iface: {
    handler: deleteNetworkIface,
    schema: deleteNetworkIfaceSchema,
  },
  proxmox_apply_network_config: {
    handler: applyNetworkConfig,
    schema: applyNetworkConfigSchema,
  },

  // System Operations
  proxmox_get_node_time: { handler: getNodeTime, schema: getNodeTimeSchema },
  proxmox_update_node_time: { handler: updateNodeTime, schema: updateNodeTimeSchema },
  proxmox_update_node_dns: { handler: updateNodeDns, schema: updateNodeDnsSchema },
  proxmox_get_node_hosts: { handler: getNodeHosts, schema: getNodeHostsSchema },
  proxmox_update_node_hosts: {
    handler: updateNodeHosts,
    schema: updateNodeHostsSchema,
  },
  proxmox_get_node_subscription: {
    handler: getNodeSubscription,
    schema: getNodeSubscriptionSchema,
  },
  proxmox_set_node_subscription: {
    handler: setNodeSubscription,
    schema: setNodeSubscriptionSchema,
  },
  proxmox_delete_node_subscription: {
    handler: deleteNodeSubscription,
    schema: deleteNodeSubscriptionSchema,
  },
  proxmox_apt_update: { handler: aptUpdate, schema: aptUpdateSchema },
  proxmox_apt_upgrade: { handler: aptUpgrade, schema: aptUpgradeSchema },
  proxmox_apt_versions: { handler: aptVersions, schema: aptVersionsSchema },
  proxmox_start_all: { handler: startAll, schema: startAllSchema },
  proxmox_stop_all: { handler: stopAll, schema: stopAllSchema },
  proxmox_migrate_all: { handler: migrateAll, schema: migrateAllSchema },
  proxmox_node_shutdown: { handler: nodeShutdown, schema: nodeShutdownSchema },
  proxmox_node_reboot: { handler: nodeReboot, schema: nodeRebootSchema },
  proxmox_node_wakeonlan: { handler: nodeWakeonlan, schema: nodeWakeonlanSchema },
  proxmox_get_node_replication_status: { handler: getNodeReplicationStatus, schema: getNodeReplicationStatusSchema },
  proxmox_get_node_replication_log: { handler: getNodeReplicationLog, schema: getNodeReplicationLogSchema },
  proxmox_schedule_node_replication: { handler: scheduleNodeReplication, schema: scheduleNodeReplicationSchema },

  // Cluster Management
  proxmox_get_ha_resources: { handler: getHaResources, schema: getHaResourcesSchema },
  proxmox_get_ha_resource: { handler: getHaResource, schema: getHaResourceSchema },
  proxmox_create_ha_resource: { handler: createHaResource, schema: createHaResourceSchema },
  proxmox_update_ha_resource: { handler: updateHaResource, schema: updateHaResourceSchema },
  proxmox_delete_ha_resource: { handler: deleteHaResource, schema: deleteHaResourceSchema },
  proxmox_get_ha_groups: { handler: getHaGroups, schema: getHaGroupsSchema },
  proxmox_get_ha_group: { handler: getHaGroup, schema: getHaGroupSchema },
  proxmox_create_ha_group: { handler: createHaGroup, schema: createHaGroupSchema },
  proxmox_update_ha_group: { handler: updateHaGroup, schema: updateHaGroupSchema },
  proxmox_delete_ha_group: { handler: deleteHaGroup, schema: deleteHaGroupSchema },
  proxmox_get_ha_status: { handler: getHaStatus, schema: getHaStatusSchema },
  proxmox_list_cluster_firewall_rules: {
    handler: listClusterFirewallRules,
    schema: listClusterFirewallRulesSchema,
  },
  proxmox_get_cluster_firewall_rule: {
    handler: getClusterFirewallRule,
    schema: getClusterFirewallRuleSchema,
  },
  proxmox_create_cluster_firewall_rule: {
    handler: createClusterFirewallRule,
    schema: createClusterFirewallRuleSchema,
  },
  proxmox_update_cluster_firewall_rule: {
    handler: updateClusterFirewallRule,
    schema: updateClusterFirewallRuleSchema,
  },
  proxmox_delete_cluster_firewall_rule: {
    handler: deleteClusterFirewallRule,
    schema: deleteClusterFirewallRuleSchema,
  },
  proxmox_list_cluster_firewall_groups: {
    handler: listClusterFirewallGroups,
    schema: listClusterFirewallGroupsSchema,
  },
  proxmox_get_cluster_firewall_group: {
    handler: getClusterFirewallGroup,
    schema: getClusterFirewallGroupSchema,
  },
  proxmox_create_cluster_firewall_group: {
    handler: createClusterFirewallGroup,
    schema: createClusterFirewallGroupSchema,
  },
  proxmox_update_cluster_firewall_group: {
    handler: updateClusterFirewallGroup,
    schema: updateClusterFirewallGroupSchema,
  },
  proxmox_delete_cluster_firewall_group: {
    handler: deleteClusterFirewallGroup,
    schema: deleteClusterFirewallGroupSchema,
  },
  proxmox_list_cluster_backup_jobs: {
    handler: listClusterBackupJobs,
    schema: listClusterBackupJobsSchema,
  },
  proxmox_get_cluster_backup_job: {
    handler: getClusterBackupJob,
    schema: getClusterBackupJobSchema,
  },
  proxmox_create_cluster_backup_job: {
    handler: createClusterBackupJob,
    schema: createClusterBackupJobSchema,
  },
  proxmox_update_cluster_backup_job: {
    handler: updateClusterBackupJob,
    schema: updateClusterBackupJobSchema,
  },
  proxmox_delete_cluster_backup_job: {
    handler: deleteClusterBackupJob,
    schema: deleteClusterBackupJobSchema,
  },
  proxmox_list_cluster_replication_jobs: {
    handler: listClusterReplicationJobs,
    schema: listClusterReplicationJobsSchema,
  },
  proxmox_get_cluster_replication_job: {
    handler: getClusterReplicationJob,
    schema: getClusterReplicationJobSchema,
  },
  proxmox_create_cluster_replication_job: {
    handler: createClusterReplicationJob,
    schema: createClusterReplicationJobSchema,
  },
  proxmox_update_cluster_replication_job: {
    handler: updateClusterReplicationJob,
    schema: updateClusterReplicationJobSchema,
  },
  proxmox_delete_cluster_replication_job: {
    handler: deleteClusterReplicationJob,
    schema: deleteClusterReplicationJobSchema,
  },
  proxmox_get_cluster_options: { handler: getClusterOptions, schema: getClusterOptionsSchema },
  proxmox_update_cluster_options: {
    handler: updateClusterOptions,
    schema: updateClusterOptionsSchema,
  },
  proxmox_get_cluster_firewall_options: {
    handler: getClusterFirewallOptions,
    schema: getClusterFirewallOptionsSchema,
  },
  proxmox_update_cluster_firewall_options: {
    handler: updateClusterFirewallOptions,
    schema: updateClusterFirewallOptionsSchema,
  },
  proxmox_list_cluster_firewall_macros: {
    handler: listClusterFirewallMacros,
    schema: listClusterFirewallMacrosSchema,
  },
   proxmox_list_cluster_firewall_refs: {
     handler: listClusterFirewallRefs,
     schema: listClusterFirewallRefsSchema,
   },
   proxmox_list_cluster_firewall_aliases: {
     handler: listClusterFirewallAliases,
     schema: listClusterFirewallAliasesSchema,
   },
   proxmox_get_cluster_firewall_alias: {
     handler: getClusterFirewallAlias,
     schema: getClusterFirewallAliasSchema,
   },
   proxmox_create_cluster_firewall_alias: {
     handler: createClusterFirewallAlias,
     schema: createClusterFirewallAliasSchema,
   },
   proxmox_update_cluster_firewall_alias: {
     handler: updateClusterFirewallAlias,
     schema: updateClusterFirewallAliasSchema,
   },
   proxmox_delete_cluster_firewall_alias: {
     handler: deleteClusterFirewallAlias,
     schema: deleteClusterFirewallAliasSchema,
   },
   proxmox_list_cluster_firewall_ipsets: {
     handler: listClusterFirewallIpsets,
     schema: listClusterFirewallIpsetsSchema,
   },
   proxmox_create_cluster_firewall_ipset: {
     handler: createClusterFirewallIpset,
     schema: createClusterFirewallIpsetSchema,
   },
   proxmox_delete_cluster_firewall_ipset: {
     handler: deleteClusterFirewallIpset,
     schema: deleteClusterFirewallIpsetSchema,
   },
   proxmox_list_cluster_firewall_ipset_entries: {
     handler: listClusterFirewallIpsetEntries,
     schema: listClusterFirewallIpsetEntriesSchema,
   },
   proxmox_add_cluster_firewall_ipset_entry: {
     handler: addClusterFirewallIpsetEntry,
     schema: addClusterFirewallIpsetEntrySchema,
   },
   proxmox_update_cluster_firewall_ipset_entry: {
     handler: updateClusterFirewallIpsetEntry,
     schema: updateClusterFirewallIpsetEntrySchema,
   },
   proxmox_delete_cluster_firewall_ipset_entry: {
     handler: deleteClusterFirewallIpsetEntry,
     schema: deleteClusterFirewallIpsetEntrySchema,
   },

  // SDN
  proxmox_list_sdn_vnets: { handler: listSdnVnets, schema: listSdnVnetsSchema },
  proxmox_get_sdn_vnet: { handler: getSdnVnet, schema: getSdnVnetSchema },
  proxmox_create_sdn_vnet: { handler: createSdnVnet, schema: createSdnVnetSchema },
  proxmox_update_sdn_vnet: { handler: updateSdnVnet, schema: updateSdnVnetSchema },
  proxmox_delete_sdn_vnet: { handler: deleteSdnVnet, schema: deleteSdnVnetSchema },
  proxmox_list_sdn_zones: { handler: listSdnZones, schema: listSdnZonesSchema },
  proxmox_get_sdn_zone: { handler: getSdnZone, schema: getSdnZoneSchema },
  proxmox_create_sdn_zone: { handler: createSdnZone, schema: createSdnZoneSchema },
  proxmox_update_sdn_zone: { handler: updateSdnZone, schema: updateSdnZoneSchema },
  proxmox_delete_sdn_zone: { handler: deleteSdnZone, schema: deleteSdnZoneSchema },
  proxmox_list_sdn_controllers: {
    handler: listSdnControllers,
    schema: listSdnControllersSchema,
  },
  proxmox_get_sdn_controller: { handler: getSdnController, schema: getSdnControllerSchema },
  proxmox_create_sdn_controller: {
    handler: createSdnController,
    schema: createSdnControllerSchema,
  },
  proxmox_update_sdn_controller: {
    handler: updateSdnController,
    schema: updateSdnControllerSchema,
  },
  proxmox_delete_sdn_controller: {
    handler: deleteSdnController,
    schema: deleteSdnControllerSchema,
  },
  proxmox_list_sdn_subnets: { handler: listSdnSubnets, schema: listSdnSubnetsSchema },
  proxmox_get_sdn_subnet: { handler: getSdnSubnet, schema: getSdnSubnetSchema },
  proxmox_create_sdn_subnet: { handler: createSdnSubnet, schema: createSdnSubnetSchema },
  proxmox_update_sdn_subnet: { handler: updateSdnSubnet, schema: updateSdnSubnetSchema },
  proxmox_delete_sdn_subnet: { handler: deleteSdnSubnet, schema: deleteSdnSubnetSchema },

  // Access Control
  proxmox_list_users: { handler: listUsers, schema: listUsersSchema },
  proxmox_get_user: { handler: getUser, schema: getUserSchema },
  proxmox_create_user: { handler: createUser, schema: createUserSchema },
  proxmox_update_user: { handler: updateUser, schema: updateUserSchema },
  proxmox_delete_user: { handler: deleteUser, schema: deleteUserSchema },
  proxmox_list_groups: { handler: listGroups, schema: listGroupsSchema },
  proxmox_create_group: { handler: createGroup, schema: createGroupSchema },
  proxmox_update_group: { handler: updateGroup, schema: updateGroupSchema },
  proxmox_delete_group: { handler: deleteGroup, schema: deleteGroupSchema },
  proxmox_list_roles: { handler: listRoles, schema: listRolesSchema },
  proxmox_create_role: { handler: createRole, schema: createRoleSchema },
  proxmox_update_role: { handler: updateRole, schema: updateRoleSchema },
  proxmox_delete_role: { handler: deleteRole, schema: deleteRoleSchema },
  proxmox_get_acl: { handler: getAcl, schema: getAclSchema },
  proxmox_update_acl: { handler: updateAcl, schema: updateAclSchema },
  proxmox_list_domains: { handler: listDomains, schema: listDomainsSchema },
  proxmox_get_domain: { handler: getDomain, schema: getDomainSchema },
  proxmox_create_domain: { handler: createDomain, schema: createDomainSchema },
  proxmox_update_domain: { handler: updateDomain, schema: updateDomainSchema },
  proxmox_delete_domain: { handler: deleteDomain, schema: deleteDomainSchema },

  // User API Tokens
  proxmox_list_user_tokens: { handler: listUserTokens, schema: listUserTokensSchema },
  proxmox_get_user_token: { handler: getUserToken, schema: getUserTokenSchema },
  proxmox_create_user_token: { handler: createUserToken, schema: createUserTokenSchema },
  proxmox_update_user_token: { handler: updateUserToken, schema: updateUserTokenSchema },
  proxmox_delete_user_token: { handler: deleteUserToken, schema: deleteUserTokenSchema },

  // Pool Management
  proxmox_list_pools: { handler: listPools, schema: listPoolsSchema },
  proxmox_get_pool: { handler: getPool, schema: getPoolSchema },
  proxmox_create_pool: { handler: createPool, schema: createPoolSchema },
  proxmox_update_pool: { handler: updatePool, schema: updatePoolSchema },
  proxmox_delete_pool: { handler: deletePool, schema: deletePoolSchema },

  // Storage Management
  proxmox_list_storage_config: {
    handler: listStorageConfig,
    schema: listStorageConfigSchema,
  },
  proxmox_get_storage_config: { handler: getStorageConfig, schema: getStorageConfigSchema },
  proxmox_create_storage: { handler: createStorage, schema: createStorageSchema },
  proxmox_update_storage: { handler: updateStorage, schema: updateStorageSchema },
  proxmox_delete_storage: { handler: deleteStorage, schema: deleteStorageSchema },
  proxmox_upload_to_storage: { handler: uploadToStorage, schema: uploadToStorageSchema },
  proxmox_download_url_to_storage: {
    handler: downloadUrlToStorage,
    schema: downloadUrlToStorageSchema,
  },
  proxmox_list_storage_content: {
    handler: listStorageContent,
    schema: listStorageContentSchema,
  },
  proxmox_delete_storage_content: {
    handler: deleteStorageContent,
    schema: deleteStorageContentSchema,
  },
  proxmox_list_file_restore: { handler: listFileRestore, schema: listFileRestoreSchema },
  proxmox_download_file_restore: {
    handler: downloadFileRestore,
    schema: downloadFileRestoreSchema,
  },
  proxmox_prune_backups: { handler: pruneBackups, schema: pruneBackupsSchema },

  // Ceph Integration
  proxmox_get_ceph_status: { handler: getCephStatus, schema: getCephStatusSchema },
  proxmox_list_ceph_osds: { handler: listCephOsds, schema: listCephOsdsSchema },
  proxmox_create_ceph_osd: { handler: createCephOsd, schema: createCephOsdSchema },
  proxmox_delete_ceph_osd: { handler: deleteCephOsd, schema: deleteCephOsdSchema },
  proxmox_list_ceph_mons: { handler: listCephMons, schema: listCephMonsSchema },
  proxmox_create_ceph_mon: { handler: createCephMon, schema: createCephMonSchema },
  proxmox_delete_ceph_mon: { handler: deleteCephMon, schema: deleteCephMonSchema },
  proxmox_list_ceph_mds: { handler: listCephMds, schema: listCephMdsSchema },
  proxmox_create_ceph_mds: { handler: createCephMds, schema: createCephMdsSchema },
  proxmox_delete_ceph_mds: { handler: deleteCephMds, schema: deleteCephMdsSchema },
  proxmox_list_ceph_pools: { handler: listCephPools, schema: listCephPoolsSchema },
  proxmox_create_ceph_pool: { handler: createCephPool, schema: createCephPoolSchema },
  proxmox_update_ceph_pool: { handler: updateCephPool, schema: updateCephPoolSchema },
  proxmox_delete_ceph_pool: { handler: deleteCephPool, schema: deleteCephPoolSchema },
  proxmox_list_ceph_fs: { handler: listCephFs, schema: listCephFsSchema },
  proxmox_create_ceph_fs: { handler: createCephFs, schema: createCephFsSchema },

  // Console Access
  proxmox_get_vnc_proxy: { handler: getVncProxy, schema: getVncProxySchema },
  proxmox_get_spice_proxy: { handler: getSpiceProxy, schema: getSpiceProxySchema },
  proxmox_get_term_proxy: { handler: getTermProxy, schema: getTermProxySchema },
  proxmox_get_lxc_vnc_proxy: {
    handler: getLxcVncProxy,
    schema: getLxcVncProxySchema,
  },
  proxmox_get_lxc_term_proxy: {
    handler: getLxcTermProxy,
    schema: getLxcTermProxySchema,
  },

  // Node Management
  proxmox_get_node_services: { handler: getNodeServices, schema: getNodeServicesSchema },
  proxmox_control_node_service: {
    handler: controlNodeService,
    schema: controlNodeServiceSchema,
  },
  proxmox_get_node_syslog: { handler: getNodeSyslog, schema: getNodeSyslogSchema },
  proxmox_get_node_journal: { handler: getNodeJournal, schema: getNodeJournalSchema },
  proxmox_get_node_tasks: { handler: getNodeTasks, schema: getNodeTasksSchema },
  proxmox_get_node_task: { handler: getNodeTask, schema: getNodeTaskSchema },
  proxmox_get_node_aplinfo: { handler: getNodeAplinfo, schema: getNodeAplinfoSchema },
  proxmox_get_node_netstat: { handler: getNodeNetstat, schema: getNodeNetstatSchema },
  proxmox_get_node_rrddata: { handler: getNodeRrddata, schema: getNodeRrddataSchema },
  proxmox_get_storage_rrddata: { handler: getStorageRrddata, schema: getStorageRrddataSchema },
  proxmox_get_node_report: { handler: getNodeReport, schema: getNodeReportSchema },

  // VM Query
  proxmox_get_vms: { handler: getVMs, schema: getVmsSchema },
  proxmox_get_vm_status: { handler: getVMStatus, schema: getVmStatusSchema },
  proxmox_get_vm_config: { handler: getVMConfig, schema: getVmConfigSchema },
  proxmox_get_lxc_config: { handler: getLxcConfig, schema: getLxcConfigSchema },
  proxmox_get_storage: { handler: getStorage, schema: getStorageSchema },

  // VM Lifecycle
  proxmox_start_lxc: { handler: startLxc, schema: startLxcSchema },
  proxmox_start_vm: { handler: startVM, schema: startVmSchema },
  proxmox_stop_lxc: { handler: stopLxc, schema: stopLxcSchema },
  proxmox_stop_vm: { handler: stopVM, schema: stopVmSchema },
  proxmox_delete_lxc: { handler: deleteLxc, schema: deleteLxcSchema },
  proxmox_delete_vm: { handler: deleteVM, schema: deleteVmSchema },
  proxmox_reboot_lxc: { handler: rebootLxc, schema: rebootLxcSchema },
  proxmox_reboot_vm: { handler: rebootVM, schema: rebootVmSchema },
  proxmox_shutdown_lxc: { handler: shutdownLxc, schema: shutdownLxcSchema },
  proxmox_shutdown_vm: { handler: shutdownVM, schema: shutdownVmSchema },
  proxmox_pause_vm: { handler: pauseVM, schema: pauseVmSchema },
  proxmox_resume_vm: { handler: resumeVM, schema: resumeVmSchema },

  // VM Modify
  proxmox_clone_lxc: { handler: cloneLxc, schema: cloneLxcSchema },
  proxmox_clone_vm: { handler: cloneVM, schema: cloneVmSchema },
  proxmox_resize_lxc: { handler: resizeLxc, schema: resizeLxcSchema },
  proxmox_resize_vm: { handler: resizeVM, schema: resizeVmSchema },

  // VM/LXC Advanced
  proxmox_migrate_vm: { handler: migrateVm, schema: migrateVmSchema },
  proxmox_migrate_lxc: { handler: migrateLxc, schema: migrateLxcSchema },
  proxmox_create_template_vm: { handler: createTemplateVm, schema: createTemplateVmSchema },
  proxmox_create_template_lxc: { handler: createTemplateLxc, schema: createTemplateLxcSchema },
  proxmox_get_vm_rrddata: { handler: getVmRrddata, schema: getVmRrddataSchema },
  proxmox_get_lxc_rrddata: { handler: getLxcRrddata, schema: getLxcRrddataSchema },
  proxmox_agent_ping: { handler: agentPing, schema: agentPingSchema },
  proxmox_agent_get_osinfo: { handler: agentGetOsinfo, schema: agentGetOsinfoSchema },
  proxmox_agent_get_fsinfo: { handler: agentGetFsinfo, schema: agentGetFsinfoSchema },
  proxmox_agent_get_memory_blocks: {
    handler: agentGetMemoryBlocks,
    schema: agentGetMemoryBlocksSchema,
  },
  proxmox_agent_get_network_interfaces: {
    handler: agentGetNetworkInterfaces,
    schema: agentGetNetworkInterfacesSchema,
  },
  proxmox_agent_get_time: { handler: agentGetTime, schema: agentGetTimeSchema },
  proxmox_agent_get_timezone: { handler: agentGetTimezone, schema: agentGetTimezoneSchema },
  proxmox_agent_get_vcpus: { handler: agentGetVcpus, schema: agentGetVcpusSchema },
   proxmox_agent_exec: { handler: agentExec, schema: agentExecSchema },
   proxmox_agent_exec_status: { handler: agentExecStatus, schema: agentExecStatusSchema },
   proxmox_agent_file_read: { handler: agentFileRead, schema: agentFileReadSchema },
   proxmox_agent_file_write: { handler: agentFileWrite, schema: agentFileWriteSchema },
   proxmox_agent_get_hostname: { handler: agentGetHostname, schema: agentGetHostnameSchema },
   proxmox_agent_get_users: { handler: agentGetUsers, schema: agentGetUsersSchema },
   proxmox_agent_set_user_password: { handler: agentSetUserPassword, schema: agentSetUserPasswordSchema },
   proxmox_agent_shutdown: { handler: agentShutdown, schema: agentShutdownSchema },
   proxmox_agent_fsfreeze_status: { handler: agentFsfreezeStatus, schema: agentFsfreezeStatusSchema },
   proxmox_agent_fsfreeze_freeze: { handler: agentFsfreezeFreeze, schema: agentFsfreezeFreezeSchema },
   proxmox_agent_fsfreeze_thaw: { handler: agentFsfreezeThaw, schema: agentFsfreezeThawSchema },
   proxmox_agent_fstrim: { handler: agentFstrim, schema: agentFstrimSchema },
   proxmox_agent_get_memory_block_info: { handler: agentGetMemoryBlockInfo, schema: agentGetMemoryBlockInfoSchema },
   proxmox_agent_suspend_disk: { handler: agentSuspendDisk, schema: agentSuspendDiskSchema },
   proxmox_agent_suspend_ram: { handler: agentSuspendRam, schema: agentSuspendRamSchema },
   proxmox_agent_suspend_hybrid: { handler: agentSuspendHybrid, schema: agentSuspendHybridSchema },
   proxmox_list_vm_firewall_rules: {
    handler: listVmFirewallRules,
    schema: listVmFirewallRulesSchema,
  },
  proxmox_get_vm_firewall_rule: { handler: getVmFirewallRule, schema: getVmFirewallRuleSchema },
  proxmox_create_vm_firewall_rule: {
    handler: createVmFirewallRule,
    schema: createVmFirewallRuleSchema,
  },
  proxmox_update_vm_firewall_rule: {
    handler: updateVmFirewallRule,
    schema: updateVmFirewallRuleSchema,
  },
  proxmox_delete_vm_firewall_rule: {
    handler: deleteVmFirewallRule,
    schema: deleteVmFirewallRuleSchema,
  },
  proxmox_list_lxc_firewall_rules: {
    handler: listLxcFirewallRules,
    schema: listLxcFirewallRulesSchema,
  },
  proxmox_get_lxc_firewall_rule: {
    handler: getLxcFirewallRule,
    schema: getLxcFirewallRuleSchema,
  },
  proxmox_create_lxc_firewall_rule: {
    handler: createLxcFirewallRule,
    schema: createLxcFirewallRuleSchema,
  },
  proxmox_update_lxc_firewall_rule: {
    handler: updateLxcFirewallRule,
    schema: updateLxcFirewallRuleSchema,
  },
  proxmox_delete_lxc_firewall_rule: {
    handler: deleteLxcFirewallRule,
    schema: deleteLxcFirewallRuleSchema,
  },

  // Snapshots
  proxmox_create_snapshot_lxc: { handler: createSnapshotLxc, schema: createSnapshotLxcSchema },
  proxmox_create_snapshot_vm: { handler: createSnapshotVM, schema: createSnapshotVmSchema },
  proxmox_list_snapshots_lxc: { handler: listSnapshotsLxc, schema: listSnapshotsLxcSchema },
  proxmox_list_snapshots_vm: { handler: listSnapshotsVM, schema: listSnapshotsVmSchema },
  proxmox_rollback_snapshot_lxc: { handler: rollbackSnapshotLxc, schema: rollbackSnapshotLxcSchema },
  proxmox_rollback_snapshot_vm: { handler: rollbackSnapshotVM, schema: rollbackSnapshotVmSchema },
  proxmox_delete_snapshot_lxc: { handler: deleteSnapshotLxc, schema: deleteSnapshotLxcSchema },
  proxmox_delete_snapshot_vm: { handler: deleteSnapshotVM, schema: deleteSnapshotVmSchema },

  // Backups
  proxmox_create_backup_lxc: { handler: createBackupLxc, schema: createBackupLxcSchema },
  proxmox_create_backup_vm: { handler: createBackupVM, schema: createBackupVmSchema },
  proxmox_list_backups: { handler: listBackups, schema: listBackupsSchema },
  proxmox_restore_backup_lxc: { handler: restoreBackupLxc, schema: restoreBackupLxcSchema },
  proxmox_restore_backup_vm: { handler: restoreBackupVM, schema: restoreBackupVmSchema },
  proxmox_delete_backup: { handler: deleteBackup, schema: deleteBackupSchema },

   // Disks
   proxmox_add_disk_vm: { handler: addDiskVM, schema: addDiskVmSchema },
   proxmox_add_mountpoint_lxc: { handler: addMountpointLxc, schema: addMountpointLxcSchema },
   proxmox_resize_disk_vm: { handler: resizeDiskVM, schema: resizeDiskVmSchema },
   proxmox_resize_disk_lxc: { handler: resizeDiskLxc, schema: resizeDiskLxcSchema },
   proxmox_remove_disk_vm: { handler: removeDiskVM, schema: removeDiskVmSchema },
   proxmox_remove_mountpoint_lxc: { handler: removeMountpointLxc, schema: removeMountpointLxcSchema },
   proxmox_move_disk_vm: { handler: moveDiskVM, schema: moveDiskVmSchema },
   proxmox_move_disk_lxc: { handler: moveDiskLxc, schema: moveDiskLxcSchema },
   proxmox_get_node_disks: { handler: getNodeDisks, schema: getNodeDisksSchema },
   proxmox_get_disk_smart: { handler: getDiskSmart, schema: getDiskSmartSchema },
   proxmox_get_node_lvm: { handler: getNodeLvm, schema: getNodeLvmSchema },
   proxmox_get_node_zfs: { handler: getNodeZfs, schema: getNodeZfsSchema },

  // Network
  proxmox_add_network_vm: { handler: addNetworkVm, schema: addNetworkVmSchema },
  proxmox_add_network_lxc: { handler: addNetworkLxc, schema: addNetworkLxcSchema },
  proxmox_update_network_vm: { handler: updateNetworkVm, schema: updateNetworkVmSchema },
  proxmox_update_network_lxc: { handler: updateNetworkLxc, schema: updateNetworkLxcSchema },
  proxmox_remove_network_vm: { handler: removeNetworkVm, schema: removeNetworkVmSchema },
  proxmox_remove_network_lxc: { handler: removeNetworkLxc, schema: removeNetworkLxcSchema },

  // Command
  proxmox_execute_vm_command: { handler: executeVMCommand, schema: executeVmCommandSchema },

   // Creation
   proxmox_list_templates: { handler: listTemplates, schema: listTemplatesSchema },
   proxmox_create_lxc: { handler: createLxc, schema: createLxcSchema },
   proxmox_create_vm: { handler: createVM, schema: createVmSchema },

   // Cloud-Init
   proxmox_get_cloudinit_config: { handler: getCloudInitConfig, schema: getCloudInitConfigSchema },
   proxmox_dump_cloudinit: { handler: dumpCloudInit, schema: dumpCloudInitSchema },
   proxmox_regenerate_cloudinit: { handler: regenerateCloudInit, schema: regenerateCloudInitSchema },
};

// Helper to get tool handler
export function getToolHandler(toolName: ToolName): ToolRegistryEntry | undefined {
  return toolRegistry[toolName];
}

// Validate all 274 tools are registered
const registeredCount = Object.keys(toolRegistry).length;
if (registeredCount !== 274) {
  throw new Error(
    `Tool registry incomplete: expected 274 tools, got ${registeredCount}`
  );
}
